version = '230127'

['预算'.'饮食']
# 包含请客吃饭
'吃饭'.'类型' = '日结'
'吃饭'.'在校' = 39
'吃饭'.'在家' = 5.55

'饮料'.'类型' = '日结'
'饮料'.'在校' = 7.1
'饮料'.'在家' = 0.2

'水果牛奶'.'类型' = '日结'
'水果牛奶'.'在校' = 4.2
'水果牛奶'.'在家' = 3.9

'零食冷饮'.'类型' = '日结'
'零食冷饮'.'在校' = 2.1

['预算'.'生活']
'耐用品'.'类型' = '日结'
'耐用品'.'在校' = 2.52

'服装外形'.'类型' = '月结'
'服装外形'.'每月' = 189

'交通物流'.'类型' = '月结'
'交通物流'.'每月' = 115

'医疗'.'类型' = '月结'
'医疗'.'每月' = 33

'日用消耗'.'类型' = '月结'
'日用消耗'.'每月' = 27

'赠礼'.'类型' = '月结'
'赠礼'.'每月' = 20

['预算'.'学习']
# 付费软件，培训费，报名费，服务器
'软件服务'.'类型' = '月结'
'软件服务'.'每月' = 136
# 资料费，买书，等等
'文具资料'.'类型' = '月结'
'文具资料'.'每月' = 21

['预算'.'娱乐']
'小说'.'类型' = '月结'
'小说'.'每月' = 75

'视频游戏'.'类型' = '月结'
'视频游戏'.'每月' = 50

'其它娱乐'.'类型' = '月结'
'其它娱乐'.'每月' = 30

['预算'.'数码']
'主机'.'类型' = '月结'
'主机'.'每月' = 330

'配件'.'类型' = '月结'
'配件'.'每月' = 23

['预算'.'杂费']
# 杂费都按日计算

'洗衣'.'类型' = '季节'
# 夏季的定义：6 7 8 9 月。
'洗衣'.'在校'.'夏季' = 1.4
# 其余的月份都视为春秋季。
'洗衣'.'在校'.'春秋' = 1.25
# 冬季的定义：11 12 1 2 月。
'洗衣'.'在校'.'冬季' = 0.9

'电力'.'类型' = '特殊'
'电力'.'基础' = 0.181

# 空调的费用是 n 个人均摊的。
# 由于留校等因素影响，人数 n 不确定。
'电力'.'夏季'.'在校' = 0.9
'电力'.'夏季'.'算法' = 'n+2/n'

'电力'.'冬季'.'在校' = 0.81
'电力'.'冬季'.'算法' = '6-n/n'

'其他'.'类型' = '月结'
'其他'.'每月' = 73